package com.railopt.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Represents a single maintenance task in the Indian Railway system.
 *
 * Each task belongs to one Department and describes work to be done
 * on a specific asset (track, signal, OHE, etc.) at a given location.
 *
 * Future: This entity will be linked to MaintenanceBlock when the
 * planning/conflict engine module is implemented.
 */
@Entity
@Table(name = "maintenance_tasks", uniqueConstraints = {
        @UniqueConstraint(name = "uk_task_id", columnNames = "task_id")
})
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class MaintenanceTask {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Human-readable unique task identifier, e.g. "TASK-PWAY-001".
     * Generated by the client or service — must be globally unique.
     */
    @NotBlank
    @Size(max = 50)
    @Column(name = "task_id", nullable = false, unique = true)
    private String taskId;

    /** Owning department (e.g. P-Way, TRD, S&T) */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "department_id", nullable = false)
    private Department department;

    /** Asset under maintenance, e.g. "Track TDL-162", "Signal ALJN-44" */
    @NotBlank
    @Size(max = 200)
    @Column(nullable = false)
    private String assetName;

    /** Railway location / chainage, e.g. "ALJN Yard", "CNB-105 km" */
    @NotBlank
    @Size(max = 200)
    @Column(nullable = false)
    private String location;

    /** Category of work, e.g. "Inspection", "Replacement", "Calibration" */
    @NotBlank
    @Size(max = 100)
    @Column(nullable = false)
    private String taskType;

    @Size(max = 1000)
    @Column(length = 1000)
    private String description;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    @Builder.Default
    private Severity severity = Severity.MEDIUM;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    @Builder.Default
    private Priority priority = Priority.MEDIUM;

    /** Duration the track/asset needs to be blocked in minutes */
    @Positive
    @Column(nullable = false)
    private Integer durationMinutes;

    /** Target completion date */
    @FutureOrPresent
    private LocalDate dueDate;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    @Builder.Default
    private TaskStatus status = TaskStatus.PENDING;

    @CreationTimestamp
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(nullable = false)
    private LocalDateTime updatedAt;
}
